require: rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/tasks/auto_annotate_models.rake"

Layout/LineLength:
  Max: 90
  IgnoredPatterns:
    - '\A(\s)*#'

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
